DROP TABLE Vehicule CASCADE CONSTRAINTS;
DROP TABLE Permise CASCADE CONSTRAINTS;
DROP TABLE Localitati CASCADE CONSTRAINTS;
DROP TABLE Soferi CASCADE CONSTRAINTS;
DROP TABLE Contraventii CASCADE CONSTRAINTS;
DROP TABLE Contraventii_Viteza CASCADE CONSTRAINTS;
DROP TABLE Plati_Amenzi CASCADE CONSTRAINTS;